name: FastAPI CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: [self-hosted]
    defaults:
      run:
        working-directory: ./backend

    steps:
      # 1️⃣ Checkout repo
      - uses: actions/checkout@v4
      
      - name: Clean Python artifacts
        run: find $GITHUB_WORKSPACE/backend -name '*.pyc' -delete

      # 2️⃣ Copy environment file
      - name: Copy environment file
        run: cp /home/harif/envs/wc-solutions.env .env

      # 3️⃣ Stop old containers and remove volumes (optional clean build)
      - name: Stop old containers
        run: docker compose down || true

      # 4️⃣ Build and start containers
      - name: Build and start containers
        run: docker compose up -d --build

      # 6️⃣ Stop containers after tests
      - name: Stop containers
        if: always()
        run: docker compose down
